from collections.abc import Generator
from typing import Any

from dify_plugin import Tool
from dify_plugin.entities.tool import ToolInvokeMessage
from _config import (
    API_BASE,
    DEFAULT_TIMEOUT,
    safe_api_call,
    validate_image_input,
    validate_url_input,
    yield_error,
)


class ProcessImageTool(Tool):
    def _invoke(self, tool_parameters: dict[str, Any]) -> Generator[ToolInvokeMessage]:
        api_key = self.runtime.credentials["pixseo_api_key"]
        headers = {"X-API-Key": api_key, "Content-Type": "application/json"}

        image_base64 = tool_parameters.get("image_base64", "")
        file_url = tool_parameters.get("file_url", "")

        if not image_base64 and not file_url:
            yield from yield_error(
                self, "either image_base64 or file_url is required"
            )
            return

        if image_base64:
            err = validate_image_input(image_base64)
            if err:
                yield from yield_error(self, err)
                return

        if file_url:
            err = validate_url_input(file_url)
            if err:
                yield from yield_error(self, err)
                return

        payload: dict[str, Any] = {
            "remove_bg": tool_parameters.get("remove_bg", True),
            "compress": tool_parameters.get("compress", True),
            "return_image": True,
            "privacy_accepted": tool_parameters.get("privacy_accepted", False),
        }
        if image_base64:
            payload["image_base64"] = image_base64
        if file_url:
            payload["file_url"] = file_url

        try:
            resp = safe_api_call(
                self,
                "POST",
                f"{API_BASE}/api/v1/process/json",
                json=payload,
                headers=headers,
                timeout=DEFAULT_TIMEOUT,
            )
        except ValueError as e:
            yield from yield_error(self, str(e))
            return

        data = resp.json()
        steps = data.get("steps", {})

        result = {
            "status": "success",
            "processed_image_base64": data.get("processed_image_base64", ""),
            "reduction_percent": data.get("reduction_percent", 0),
            "original_size_kb": data.get("original_size_kb", 0),
            "processed_size_kb": data.get("processed_size_kb", 0),
            "elapsed_ms": data.get("elapsed_ms", 0),
            "privacy_notice": data.get("privacy_notice", ""),
            "steps": steps,
        }

        yield self.create_json_message(result)
        yield self.create_text_message(
            "Image processed. "
            f"Reduction: {result['reduction_percent']}%, "
            f"Elapsed: {result['elapsed_ms']}ms. "
            "Alt text should be generated by Dify LLM node."
        )
