const API_BASE_URL = '';
const AI_STATES = { LISTENING: 1, THINKING: 2, SPEAKING: 3, INTERRUPT: 4 };
const STATE_LABELS = {
  [AI_STATES.LISTENING]: "👂 Listening",
  [AI_STATES.THINKING]: "💭 Thinking",
  [AI_STATES.SPEAKING]: "💬 Speaking",
  [AI_STATES.INTERRUPT]: "⚡️ Interrupt",
};
const MESSAGE_TYPES = { CONVERSATION: 10000, STATE_CHANGE: 10001, CUSTOM_TEXT: 20000, CUSTOM_INTERRUPT: 20001, ERROR_CALLBACK: 10030, METRICS_CALLBACK: 10020 };

